import Head from "next/head";
import { useUser } from "src/hooks/useUser";
import styles from "src/components/User/User.module.css";

export const User = () => {
  const { post, user, error, isLoading } = useUser();

  if (isLoading) {
    return <div>ローディング中です</div>;
  }
  if (error) {
    return <div>{error.message}</div>;
  }

  return (
    <div>
      <Head>
        <title>{user?.name}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>{user?.name}</h1>
      <p>{user?.username}</p>
      {user?.email ? <div>email : {user?.email}</div> : null}
      <ul className={styles.list}>
        {user?.address ? <li>address : {user?.address.street}</li> : null}
        {user?.address ? <li>suite : {user?.address.suite}</li> : null}
        {user?.address ? <li>city : {user?.address.city}</li> : null}
        {user?.address ? <li>zipcode : {user?.address.zipcode}</li> : null}
      </ul>
    </div>
  );
};
