import Head from "next/head";
import { useUser } from "src/hooks/useUser";
import { PostsByUserId } from "src/components/Post/PostsByUserId";

export const User = () => {
  const { user, error, isLoading } = useUser();

  if (isLoading) {
    return <div>ローディング中です</div>;
  }
  if (error) {
    return <div>{error.message}</div>;
  }
  return (
    <div>
      <Head>
        <title>{user?.name}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1 className="font-bold text-3xl">{user?.name}</h1>
      <p className="text-lg">{user?.username}</p>
      <h2 className="font-bold text-xl mt-10">ユーザーの詳細</h2>
      {user?.email ? (
        <div className="mt-1 text-xl">email : {user?.email}</div>
      ) : null}
      <ul className="list-inside list-disc mt-2 text-xl">
        {user?.address ? (
          <li>ストリート : address : {user?.address.street}</li>
        ) : null}
        {user?.address ? <li>サイト : {user?.address.suite}</li> : null}
        {user?.address ? <li>住所 : {user?.address.city}</li> : null}
        {user?.address ? <li>コード : {user?.address.zipcode}</li> : null}
      </ul>
      <h2 className="font-bold text-xl mt-10">投稿記事</h2>
      <div className="mt-2">
        <PostsByUserId id={user.id} />
      </div>
    </div>
  );
};
