import Head from "next/head";
import { useUser } from "src/hooks/useUser";
import { PostsByUserId } from "src/components/Post/PostsByUserId";

export const User = () => {
  const { user, error, isLoading } = useUser();

  if (isLoading) {
    return <div>ローディング中です</div>;
  }
  if (error) {
    return <div>{error.message}</div>;
  }
  return (
    <div>
      <Head>
        <title>{user?.name}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>{user?.name}</h1>
      <p>{user?.username}</p>
      <h2>ユーザーの詳細</h2>
      {user?.email ? <div>email : {user?.email}</div> : null}
      <ul>
        {user?.address ? <li>address : {user?.address.street}</li> : null}
        {user?.address ? <li>suite : {user?.address.suite}</li> : null}
        {user?.address ? <li>city : {user?.address.city}</li> : null}
        {user?.address ? <li>zipcode : {user?.address.zipcode}</li> : null}
      </ul>
      <h2>投稿記事</h2>
      <PostsByUserId id={user.id} />
    </div>
  );
};
