import Head from "next/head";
import { useComment } from "src/hooks/useComment";

export const Comment = () => {
  const { comment, error, isLoading } = useComment();

  if (isLoading) {
    return <div>ローディング中です</div>;
  }
  if (error) {
    return <div>{error.message}</div>;
  }

  return (
    <div>
      <Head>
        <title>{comment?.name}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>{comment?.name}</h1>
      <p>{comment?.body}</p>
      {comment?.email ? <p>email : {comment?.email}</p> : null}
    </div>
  );
};
