import Head from "next/head";
import { Header } from "../components/Header";

const Index = () => {
  return (
    <div>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <div>
        <h1>Next.jsで学ぶReact講座</h1>
        <p>JSONplaceholderのAPIを色々叩いてみるよ！</p>
      </div>
    </div>
  );
};

export default Index;
