import Head from "next/head";
import { Header } from "src/components/Header";
import { Comments as CommentsComponents } from "src/components/Comments";

const Comments = () => {
  return (
    <div>
      <Head>
        <title>Comments Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />

      <CommentsComponents />
    </div>
  );
};

export default Comments;
